# Generated by Django 3.1.4 on 2020-12-20 01:24

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sigla')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Descripción')),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización')),
                ('transaccion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Transacción')),
                ('estado', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('primer_apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo apellido')),
                ('alias', models.CharField(blank=True, max_length=30, null=True, verbose_name='Alias')),
                ('iniciales', models.CharField(blank=True, max_length=20, null=True, verbose_name='Iniciales')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('transaccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transacción')),
                ('estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='news.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descripción')),
                ('sigla', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sigla')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha creación')),
                ('estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.usuario', verbose_name='Usuario creación')),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título')),
                ('pie', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Pie')),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha')),
                ('enlace', models.CharField(blank=True, max_length=100, null=True, verbose_name='Enlace')),
                ('ruta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ruta')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha creación')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.persona', verbose_name='Autor')),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.lugar', verbose_name='Lugar')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.usuario', verbose_name='Usuario creación')),
            ],
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descripción')),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha actualización')),
                ('transaccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transacción')),
                ('estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('usuario_actualizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formatos', to='news.usuario', verbose_name='Usuario actualización')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título')),
                ('lead', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lead')),
                ('cuerpo', models.TextField(blank=True, max_length=20000, null=True, verbose_name='Cuerpo')),
                ('enlace', models.CharField(blank=True, max_length=200, null=True, verbose_name='Enlace')),
                ('dependencia', models.IntegerField(blank=True, null=True, verbose_name='Dependencia')),
                ('autor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Autor')),
                ('visitas', models.IntegerField(blank=True, null=True, verbose_name='Visitas')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de modificación')),
                ('estado', models.CharField(blank=True, max_length=200, null=True, verbose_name='Estado')),
                ('categoria', models.ManyToManyField(to='news.Categoria', verbose_name='Categoría')),
                ('etiqueta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='news.etiqueta', verbose_name='Etiqueta')),
                ('formato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='news.formato', verbose_name='Formato')),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='news.lugar', verbose_name='Lugar')),
                ('multimedia', models.ManyToManyField(to='news.Multimedia', verbose_name='Multimedia')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='news.origen', verbose_name='Origen')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_creadas', to='news.usuario', verbose_name='Usuario creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_modificadas', to='news.usuario', verbose_name='Usuario modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Corresponsal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('biografia', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Biografía')),
                ('entidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entidad')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha fin')),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha actualización')),
                ('transaccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transacción')),
                ('estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('persona', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.persona', verbose_name='Persona')),
                ('usuario_actualizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corresponsales', to='news.usuario', verbose_name='Usuario actualización')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='news.usuario', verbose_name='Usuario de actualizacion'),
        ),
    ]
