# Generated by Django 3.1.4 on 2020-12-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_multimedia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='nivel',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='news.Categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='multimedia',
            field=models.ManyToManyField(blank=True, to='news.Multimedia', verbose_name='Multimedia'),
        ),
    ]
