# Generated by Django 3.1.4 on 2020-12-21 00:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_multimedia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='cuerpo',
            field=tinymce.models.HTMLField(blank=True, max_length=20000, null=True, verbose_name='Cuerpo'),
        ),
    ]
