# Generated by Django 3.1.4 on 2020-12-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201221_0229'),
        ('news', '0003_auto_20201221_0051'),
    ]

    operations = [
    ]
