# Generated by Django 3.1.4 on 2020-12-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_merge_20201221_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='corresponsal',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='corresponsal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='corresponsal',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Linkedin'),
        ),
        migrations.AddField(
            model_name='corresponsal',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='corresponsal',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='corresponsal',
            name='web',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Web'),
        ),
    ]
