# Generated by Django 3.1.4 on 2020-12-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20201221_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='estado',
            field=models.CharField(blank=True, choices=[('NUEVA', 'Nueva'), ('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('ELIMINADO', 'Eliminado'), ('EDITADO', 'Editado')], default='NUEVA', max_length=200, null=True, verbose_name='Estado'),
        ),
    ]
