# Generated by Django 3.1.4 on 2020-12-22 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_categoria_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corresponsal',
            name='persona',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.persona', verbose_name='Persona'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='titulo',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='nombre',
            field=models.CharField(default=' ', max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formato',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='nombre',
            field=models.CharField(default=' ', max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='titulo',
            field=models.CharField(max_length=100, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='origen',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default=' ', max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
