# Generated by Django 3.1.4 on 2020-12-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20201222_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='corresponsal',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='formato',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='origen',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creación'),
        ),
    ]
