# Generated by Django 3.1.4 on 2020-12-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20201222_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='estado',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', help_text='Marque "Activo" para habilitar esta categoría en el menú, "Inactivo" para ocultarla.', max_length=20, null=True, verbose_name='Estado'),
        ),
    ]
