# Generated by Django 3.1.4 on 2020-12-23 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20201223_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='autor',
        ),
        migrations.AddField(
            model_name='entrada',
            name='corresponsal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='news.corresponsal', verbose_name='Corresponsal'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='formato_firma',
            field=models.CharField(blank=True, choices=[('NOMBRE_ORIGEN', 'NOMBRE_ORIGEN'), ('INICIAL_ORIGEN', 'INICIAL_ORIGEN'), ('ORIGEN', 'ORIGEN')], default='ORIGEN', max_length=20, null=True, verbose_name='Formato de firma'),
        ),
    ]
