# Generated by Django 3.1.4 on 2020-12-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20201223_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='publicado',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
    ]
