# Generated by Django 3.1.4 on 2020-12-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_entrada_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='formato_firma',
            field=models.CharField(choices=[('NOMBRE_ORIGEN', 'Nombre Apellido / Origen'), ('INICIAL_ORIGEN', 'INICIALES / Origen'), ('ORIGEN', 'Origen')], default='ORIGEN', max_length=20, null=True, verbose_name='Formato de firma'),
        ),
    ]
