# Generated by Django 3.1.4 on 2020-12-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_configuracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de sección'),
        ),
    ]
