# Generated by Django 3.1.4 on 2020-12-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_auto_20201223_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='etiqueta',
            field=models.ManyToManyField(blank=True, related_name='multimedia', to='news.Etiqueta', verbose_name='Etiqueta'),
        ),
    ]
