# Generated by Django 3.1.4 on 2020-12-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_multimedia_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='formato',
            name='sigla',
            field=models.CharField(max_length=20, null=True, verbose_name='Sigla'),
        ),
    ]
