# Generated by Django 3.1.4 on 2020-12-28 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_formato_sigla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen')),
                ('multimedia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes', to='news.multimedia', verbose_name='Multimedia')),
            ],
        ),
    ]
