# Generated by Django 3.1.4 on 2020-12-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
