# Generated by Django 3.1.4 on 2020-12-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_auto_20201228_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='descargas',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Descargas'),
        ),
    ]
