# Generated by Django 3.1.4 on 2020-12-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_imagen_descargas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimedia',
            name='descargas',
        ),
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
