# Generated by Django 3.1.4 on 2021-01-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0032_auto_20210104_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='sigla',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sigla'),
        ),
    ]
