# Generated by Django 3.1.4 on 2021-01-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0034_auto_20210107_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='titulo',
            field=models.CharField(max_length=610, null=True, verbose_name='Título'),
        ),
    ]
